modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/fallOut015/glazed_bricks/issues" #optional
[[mods]] #mandatory
modId="glazed_bricks" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Glazed Bricks" #mandatory
updateJSONURL="https://raw.githubusercontent.com/fallOut015/glazed_bricks/master/src/main/resources/updates.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/glazed-bricks" #optional
logoFile="glazed_bricks.png" #optional
credits="Forge, people who made tutorials, and my friends" #optional
authors="fallOut015" #optional
description='''
A bite-sized mod that adds Glazed Bricks, slabs, stairs, and walls.
'''
[[dependencies.glazed_bricks]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.glazed_bricks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
